baseurl = "https://www.saltandsugar.tech/"
title = "å¡©ã¨ç ‚ç³–ğŸµ"
theme = "hugo_theme_robust"
languageCode = "ja-JP"
hasCJKLanguage = true
copyright = "Copyright &copy; 2020-2019, mira_tech."
googleAnalytics = "UA-132387896-1"
disqusShortname = "saltandsugar"

[params]
  description = "æ‰€è©®ã¯ä¸­å­¦ç”ŸãŒæ›¸ã„ãŸãƒ–ãƒ­ã‚° "
  dateformat = "Jan 2, 2006" # Optional
  googlefonts = "https://fonts.googleapis.com/css?family=Lobster|Lato:400,700"
  logofontfamily = "Lobster, cursive"

[params.author]
  thumbnail = "images/author.jpg"
  name = "é–“ç€¬ å¤ªé™½"
  description = "<p>ä¸­å­¦ç”Ÿã€‚ã„ã‚ã‚“ãªã“ã¨ã—ã¦éŠã‚“ã§ã‚‹ã€‚ã“ã®ãƒ–ãƒ­ã‚°ã¨ã“ã®äººã«ã¤ã„ã¦ã¯<a href='/about/what'>ã“ã¡ã‚‰</a>ã€‚</p>"
  twitter = "https://twitter.com/masetaiyo"
  github = "https://github.com/masetaiyo"
[taxonomies]

[markup.goldmark.renderer]
  unsafe = true

    