baseurl = "https://www.saltandsugar.tech/"
title = "å¡©ã¨ç ‚ç³–ğŸµ"
theme = "robust"
languageCode = "ja-JP"
hasCJKLanguage = true

disqusShortname = "saltandsugar-tech-1"

[params]
  description = "æ‰€è©®ã¯ä¸­å­¦ç”ŸãŒæ›¸ã„ãŸãƒ–ãƒ­ã‚° "
  dateformat = "Jan 2, 2006" # Optional
  # Fonts settings.
  googlefonts = "https://fonts.googleapis.com/css?family=Lobster|Lato:400,700" # Optional, Include google fonts.
  logofontfamily = "Lobster, cursive" # Optional, Override logo font.

[params.author]
  thumbnail = "images/author.jpg"
  name = "mira_tech"
  description = "<p>ä¸­å­¦ç”Ÿã€‚ã„ã‚ã‚“ãªã“ã¨ã—ã¦éŠã‚“ã§ã‚‹ã€‚ã“ã®ãƒ–ãƒ­ã‚°ã¨ã“ã®äººã«ã¤ã„ã¦ã¯<a href='/about/what'>ã“ã¡ã‚‰</a>ã€‚</p>"
  twitter = "https://twitter.com/mira_gfx"
  github = "https://github.com/mira-gfx"
  
  [taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"
    
    