baseurl = "saltandsugar.tech"
title = "å¡©ã¨ç ‚ç³–ğŸµ"
languageCode = "ja"
theme = "robust"
canonifyurls = true

#googleAnalytics = "UA-XXXXXXXX-XX" # Optional
#disqusShortname = "XYW"

[params]
  description = "æ‰€è©®ã¯ä¸­å­¦ç”ŸãŒæ›¸ã„ãŸãƒ–ãƒ­ã‚°"
  dateformat = "Jan 2, 2006" # Optional
  # Fonts settings.
  googlefonts = "https://fonts.googleapis.com/css?family=Lobster|Lato:400,700" # Optional, Include google fonts.
  fontfamily = "Lato,YuGothic,'Hiragino Kaku Gothic Pro',Meiryo,sans-serif" # Optional, Override body font family.
  logofontfamily = "Lobster, cursive" # Optional, Override logo font.

[params.author]
  thumbnail = "images/author.jpg"
  name = "mira_tech"
  description = "<p>ä¸­å­¦ç”Ÿã®ãƒ—ãƒ­ã‚°ãƒ©ãƒåˆå¿ƒè€…ğŸ”° </p><p>ã„ã‚ã‚“ãªã“ã¨ã«æ‰‹ã‚’å‡ºã—ã¦ã„ãã‚¹ã‚¿ã‚¤ãƒ«</p>"
  twitter = "https://twitter.com/mira_gfx"
  github = "https://github.com/mira-gfx"